return {
	"menteLocuaz/spectregit.nvim",
	-- Añadimos todos los comandos para que lazy-loading funcione siempre
	cmd = {
		"G",
		"Git",
		"Ggrep",
		"Glgrep",
		"Gclog",
		"Gllog",
		"Gcd",
		"Glcd",
		"Gedit",
		"Gsplit",
		"Gvsplit",
		"Gtabedit",
		"Gdiffsplit",
		"Gvdiffsplit",
		"Gread",
		"Gwrite",
		"Gblame",
		"GMove",
		"GRename",
		"GDelete",
		"GBrowse",
	},
	keys = {
		{ "<leader>ga", "<cmd>Git fetch --all -p<cr>", desc = "Git Fetch All" },
		{ "<leader>gl", "<cmd>Git pull<cr>", desc = "Git Pull" },
		{ "<leader>gs", "<cmd>Git<cr>", desc = "Git Status" },
		{ "<leader>gc", "<cmd>Git commit<cr>", desc = "Git Commit" },
		{ "<leader>gp", "<cmd>Git push<cr>", desc = "Git Push" },
	},
}
